"""``debian``: an ``install`` path list + ``permissions``/``dirs``/``fixperms``
manifests."""

from __future__ import annotations

import functools
import shlex
import typing

from ..entry import DEFAULT, FileType, _or_default
from . import (
    DumpError,
    Entries,
    MultiArtifactFormat,
    _WHITESPACE_RE,
    _has_control,
    _has_whitespace,
    _reject_control,
)


def _debian_reject(path: str, mode: str, owner: str, group: str) -> None:
    """Raise :class:`DumpError` if this entry cannot be represented in the
    debian artifacts: a control character in ``path``, then whitespace in
    ``mode``, ``owner``, or ``group`` in that order -- today's exact
    messages, used as the per-entry fallback once a batch check
    (:func:`~pkgforge.dbdump._has_control`/:func:`~pkgforge.dbdump._has_whitespace`)
    finds something wrong somewhere in the batch.
    """
    _reject_control(path, "debian")
    for field, value in (("mode", mode), ("owner", owner), ("group", group)):
        if _WHITESPACE_RE.search(value):
            raise DumpError(
                f"debian: a DB entry's {field} contains whitespace, "
                "which the permissions format cannot represent"
            )


#: Characters dh_install/dh_installdirs read as shell-glob syntax in a
#: SOURCE line, plus the backslash that escapes them; ``{``/``}`` are
#: included, so escaping them also makes a literal ``${`` read as literal
#: (``$\{``), with no separate ``$`` handling needed on the source side.
_DH_GLOB_CHARS = "\\*?[]{}"
_DH_SRC_TABLE = str.maketrans(
    {**{c: "\\" + c for c in _DH_GLOB_CHARS}, " ": "${Space}"}
)


def _dh_src(rel: str) -> str:
    """Escape a debian ``install``/``dirs`` SOURCE (debhelper compat 13+).

    Backslash-escapes every glob character so the name matches only
    itself, and ``${Space}``-escapes a literal space; a leading ``#`` (the
    line's own first character) is backslash-escaped too, since dh_install
    treats a line starting with ``#`` as a comment. A bare ``$`` is left
    alone -- see :func:`_dh_dest`.
    """
    text = rel.translate(_DH_SRC_TABLE)
    if text.startswith("#"):
        text = "\\" + text
    return text


def _dh_dest(rel: str) -> str:
    """Escape a debian ``install``/``dirs`` DESTINATION.

    dh_install never globs the destination (a backslash there is kept
    literally), so only a literal ``${`` (an unresolved compat-13 variable)
    and a space need handling; a bare ``$`` not followed by ``{`` stays
    literal, which also works on compat 12.
    """
    return rel.replace("${", "${Dollar}{").replace(" ", "${Space}")


def _dh_src_batch(rels: typing.List[str]) -> typing.List[str]:
    """:func:`_dh_src`, applied to every SOURCE in one pass: one
    ``str.translate`` over every ``rel`` newline-joined, instead of one
    Python-level call (and one ``translate``) per entry.

    Safe only because every ``rel`` here has already passed the batch's own
    control-character check (:func:`~pkgforge.dbdump._has_control`, run
    before this is ever called) -- a real ``\\n`` inside a ``rel`` would
    otherwise be indistinguishable from the join separator. The leading-``#``
    case is still per-line (it depends on each line's own first character),
    applied after the join/translate/split round-trip.
    """
    if not rels:
        return []
    lines = "\n".join(rels).translate(_DH_SRC_TABLE).split("\n")
    return ["\\" + line if line.startswith("#") else line for line in lines]


def _dh_dest_batch(rels: typing.List[str]) -> typing.List[str]:
    """:func:`_dh_dest`, applied to every DESTINATION in one pass: two
    ``str.replace`` calls over every ``rel`` newline-joined, instead of two
    Python-level calls per entry. Safe for the same reason as
    :func:`_dh_src_batch` -- every ``rel`` is already known control-free.
    """
    if not rels:
        return []
    return (
        "\n".join(rels).replace("${", "${Dollar}{").replace(" ", "${Space}").split("\n")
    )


#: The generated ``fixperms`` script's first four lines. With no pinned
#: entry, this is the whole file: ``$1`` is required (``${1:?}``, so an
#: unset or empty argument aborts before any command runs -- an empty ``$d``
#: would otherwise chmod/chown the host's own ``/usr/...``), and there is no
#: ``cd`` -- every path below is written as ``"$d"`` plus the quoted DB path
#: (DB paths always start with ``/``).
_FIXPERMS_HEADER = (
    "#!/bin/sh\n"
    "# Generated by pkgforge dbdump -f debian. Usage: sh fixperms PACKAGE-DIR\n"
    "set -e\n"
    "d=${1:?usage: sh fixperms PACKAGE-DIR}\n"
)


def _sh_word(value: str) -> str:
    """Quote ``value`` for POSIX ``sh`` (a DB path: always distinct, so this
    is never cached -- see :func:`_sh_word_cached` for owner/group/mode)."""
    return shlex.quote(value)


@functools.lru_cache(maxsize=256)
def _sh_word_cached(value: str) -> str:
    """Cached :func:`_sh_word`, for owner/group/mode values that repeat
    across many entries (unlike a path, which is unique per entry)."""
    return shlex.quote(value)


def _fixperms_lines(
    path: str, mode: str, owner: str, group: str, is_symlink: bool
) -> typing.List[str]:
    """Render PATH's ``chown``/``chgrp``/``chmod`` lines for the generated
    ``fixperms`` script (only ever called once a caller already knows at
    least one of mode/owner/group is pinned). Owner and group both pinned
    become one ``chown -- owner:group``; only one pinned uses ``chown`` or
    ``chgrp``.

    Order matches :func:`~pkgforge.entry.apply_entry`: owner (and
    group) before mode, since ``chown`` clears a regular file's setuid/setgid
    bit even to the same owner. ``-h`` targets the symlink itself for
    ``chown``/``chgrp`` (never its target); ``chmod`` is never emitted for a
    symlink at all -- POSIX ``chmod`` has no ``-h`` and would follow the
    link. ``--`` keeps an owner/group/mode that looks like an option (e.g.
    ``-x``) from being read as one.
    """
    target = '"$d"' + _sh_word(path)
    flag = "-h " if is_symlink else ""
    lines = []
    if owner != DEFAULT and group != DEFAULT:
        owner_group = _sh_word_cached(f"{owner}:{group}")
        lines.append(f"chown {flag}-- {owner_group} {target}")
    elif owner != DEFAULT:
        lines.append(f"chown {flag}-- {_sh_word_cached(owner)} {target}")
    elif group != DEFAULT:
        lines.append(f"chgrp {flag}-- {_sh_word_cached(group)} {target}")
    if mode != DEFAULT and not is_symlink:
        lines.append(f"chmod -- {_sh_word_cached(mode)} {target}")
    return lines


class Debian(MultiArtifactFormat):
    """Debian packaging artifacts built from surviving DB entries:

    * ``install`` -- ``dh_install``-style lines ``<src> <dest-dir>`` (the
      source is the build-root-relative path, debhelper-escaped; the
      destination is the entry's parent directory, escaped for ``$``/space
      only), one per non-directory entry;
    * ``permissions`` -- a pkgforge-specific ``<path> <mode> <owner>
      <group>`` manifest (unescaped: parse it right-to-left, since the path
      itself may contain spaces) for every entry that pins a non-default
      mode/owner/group;
    * ``dirs`` -- ``dh_installdirs``-style lines (dest-escaped, one per
      directory entry, in every case -- an already-populated directory is a
      harmless duplicate `mkdir`), so a directory recorded empty (``install
      -d``) still reaches the package; never routed through ``install``,
      which would re-copy any children ``--exclude`` dropped;
    * ``fixperms`` -- a POSIX ``sh`` script, always written, that applies
      every pinned mode/owner/group directly to a package directory: run it
      from ``override_dh_fixperms`` (after ``dh_fixperms``, which would
      otherwise strip the very bits this pins), e.g. ``sh debian/fixperms
      debian/<pkg>``. Per pinned entry: one ``chown owner:group`` (or
      ``chown``/``chgrp`` when only one is pinned), then ``chmod`` (chown
      before chmod, since chown clears a regular file's setuid/setgid bit
      even to the same owner); a symlink
      gets ``chown -h``/``chgrp -h`` and never a ``chmod`` (POSIX ``chmod``
      has no ``-h`` and would follow the link to a target outside the
      package tree). With no pinned entry, the script is just its own
      four-line header.

    Every entry is validated (path free of control characters; mode/owner/
    group free of whitespace) while the artifacts are built in memory; they
    are written only after :meth:`render` returns, so a
    :class:`~pkgforge.dbdump.DumpError` leaves no partial output.
    """

    NAME = "debian"
    ALIASES = ("deb",)

    def render(self, entries: Entries) -> typing.Dict[str, bytes]:
        # Resolve mode/owner/group once per entry (needed for both the batch
        # check below and the per-entry build), then validate the whole
        # batch in two regex searches instead of one control-character
        # search plus three whitespace searches per entry: a clean batch
        # (the common case) never runs a per-entry check at all. On a hit,
        # `_debian_reject` re-runs today's exact per-entry checks in entry
        # order, so the first offending entry
        # raises exactly the error it would raise rendered alone.
        resolved = [
            (
                path,
                entry,
                _or_default(entry["mode"]),
                _or_default(entry["owner"]),
                _or_default(entry["group"]),
            )
            for path, entry in entries
        ]
        if _has_control(path for path, _e, _m, _o, _g in resolved) or _has_whitespace(
            value
            for _p, _e, mode, owner, group in resolved
            for value in (mode, owner, group)
        ):
            for path, _entry, mode, owner, group in resolved:
                _debian_reject(path, mode, owner, group)

        # Two passes: gather every SOURCE/DESTINATION that needs debhelper
        # escaping first, then escape each kind in one batched call
        # (_dh_src_batch/_dh_dest_batch) instead of once per entry -- safe
        # now that the batch validation above has already ruled out a
        # control character (a literal newline included) anywhere in a
        # path. `is_dirs` is kept alongside each entry's index so the second
        # pass never has to recompute the entry's type.
        is_dirs: typing.List[bool] = []
        dest_inputs: typing.List[str] = []
        src_indices: typing.List[int] = []
        src_inputs: typing.List[str] = []
        for i, (path, entry, mode, owner, group) in enumerate(resolved):
            is_dir = entry["type"] == FileType.Directory
            rel = path.lstrip("/")
            is_dirs.append(is_dir)
            if is_dir:
                dest_inputs.append(rel)
            else:
                # rel is relative, so this equals posixpath.dirname(rel).
                dest_inputs.append(rel.rpartition("/")[0].rstrip("/"))
                src_indices.append(i)
                src_inputs.append(rel)

        escaped_dests = _dh_dest_batch(dest_inputs)
        escaped_srcs = _dh_src_batch(src_inputs)
        srcs_by_index = dict(zip(src_indices, escaped_srcs))

        install_lines: typing.List[str] = []
        perm_lines: typing.List[str] = []
        dir_lines: typing.List[str] = []
        fixperms_lines: typing.List[str] = []
        for i, (path, entry, mode, owner, group) in enumerate(resolved):
            is_symlink = entry["type"] == FileType.Symlink
            if is_dirs[i]:
                dline = escaped_dests[i]
                # dh_installdirs, like dh_install, treats a line starting
                # with "#" as a comment; "./" is a directory-neutral prefix
                # that keeps the leaf name literal instead of backslash-
                # escaping it (dh_installdirs never globs, so there is
                # nothing to escape).
                if dline.startswith("#"):
                    dline = "./" + dline
                dir_lines.append(dline)
            else:
                install_lines.append(f"{srcs_by_index[i]} {escaped_dests[i]}".rstrip())
            if mode != DEFAULT or owner != DEFAULT or group != DEFAULT:
                perm_lines.append(f"{path} {mode} {owner} {group}")
                fixperms_lines.extend(
                    _fixperms_lines(path, mode, owner, group, is_symlink)
                )

        def _join(lines: typing.List[str]) -> bytes:
            text = "\n".join(lines) + "\n" if lines else ""
            return text.encode("utf-8", "surrogateescape")

        fixperms = _FIXPERMS_HEADER.encode("utf-8", "surrogateescape") + _join(
            fixperms_lines
        )

        return {
            "install": _join(install_lines),
            "permissions": _join(perm_lines),
            "dirs": _join(dir_lines),
            "fixperms": fixperms,
        }
